CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.ANALYTICS;

USE DATABASE RETAIL_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE workshop_orders (
    order_id NUMBER PRIMARY KEY,
    customer_id VARCHAR NOT NULL,
    order_date DATE NOT NULL,
    order_status VARCHAR NOT NULL,
    gross_amount NUMBER(10, 2) NOT NULL,
    discount_amount NUMBER(10, 2) NOT NULL,
    net_amount NUMBER(10, 2) NOT NULL,
    updated_at TIMESTAMP_NTZ NOT NULL
);

